import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { tools } from "../toolsTitles";
import { readings } from "../readingsTitles";
import { formats } from "../format";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>High Noon Gamble V2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={styles.title}>Tools:</h1>
        </div>
        <div className={styles.grid}>
          {tools.map((tool) => (
            <Link href={tool.ref}>
            <img className={styles.card} src={tool.src}/>
            </Link>
          ))}
        </div>
        <div className={styles.description}>
          <h1 className={styles.title}>Readings:</h1>
        </div>
        <div className={styles.grid}>
          {readings.map((reading) => (
            <Link href={reading.ref}>
            <img className={styles.card} src={reading.src}/>
            </Link>
          ))}
        </div>
        <div className={styles.description}>
          <h1 className={styles.title}>Meeting Format:</h1>
        </div>
        <div className={styles.grid}>
          {formats.map((format) => (
            <Link href={format.ref}>
            <img className={styles.card} src={format.src}/>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
