import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { tools } from "../toolsTitles";
import { readings } from "../readingsTitles";
import {format} from "../format";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>High Noon Gamble V2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={styles.title}>Tools:</h1>
        </div>
        <div className={styles.grid}>
          {tools.map((tool) => (
            <a
              href={tool.ref}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 id={tool.toolid} className={inter.className}>
                {tool.book}
              </h2>
              <p className={inter.className}>{tool.tagline}</p>
            </a>
          ))}
        </div>
        <div className={styles.description}>
          <h1 className={styles.title}>Readings:</h1>
        </div>
        <div className={styles.grid}>
          {readings.map((reading) => (
            <a
              href={reading.ref}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>{reading.title}</h2>
              <p className={inter.className}>{reading.tagline}</p>
            </a>
          ))}
        </div>
        <div className={styles.description}>
          <h1 className={styles.title}>Meeting Format:</h1>
        </div>
        <div className={styles.grid}>
          {format.map((format) => (
            <a
              href={format.ref}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>{format.title}</h2>
              <p className={inter.className}>{format.tagline}</p>
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
